### PR TITLE
Fixing the linker switches so that CMake doesn't try to rewrite them.

### PR DESCRIPTION
**Pull request by Kelmar**
Take 2 w/o the weird reverts this time.

### CODE REVIEW

**Comment by cjntaylor** [comment]
Thanks for the updated commit. One last thing; Do you know what this does on older versions of MSVC (prior to 2015)? I was under the impression that the leading slashes we're required for MSVC flags so its news to me that the hyphens work. I'd like to try to support from 2010 forward, so I'm curious if the logic needs to be more complicated...

**Comment by Kelmar** [comment]
That's a good question, our code uses Visual Studio 2015.  Based on the CMake documentation it implies that hyphens are supposed to be used for switches, so make it handles that situation?  I'll see if I can find out for certain.

**Comment by Kelmar** [comment]
The earliest version I have installed is Visual Studio 2013, which accepts the hyphen.  According to Microsoft Visual Studio 2010's Linker should also honor the hyphen correctly.

https://msdn.microsoft.com/en-us/library/hx5b050y(v=vs.100).aspx

**Comment by cjntaylor** [comment]
Great, thanks for double checking. I'll get this merged in shortly.

**Comment by cjntaylor** [comment]
All merged in and published to npm as 2.1.1. Thanks for the help :smile:

**Pull request merged**
