### PR TITLE
Use set_target_properties instead of target_link_libraries to add LINK_FLAGS

### PR DESCRIPTION
**Pull request by kkaefer**
Since 2.0, node-cmake passes the LINK_FLAGS via `target_link_libraries`, but it should continue to use `set_target_properties` as per the [CMake document](https://cmake.org/cmake/help/v3.7/command/target_link_libraries.html?highlight=target_link_libraries#id2):

> Link flags specified here are inserted into the link command in the same place as the link libraries. This might not be correct, depending on the linker. Use the `LINK_FLAGS` target property to add link flags explicitly. The flags will then be placed at the toolchain-defined flag position in the link command.

Fixes for https://github.com/cjntaylor/node-cmake/issues/17 for non-Windows builds.

### CODE REVIEW

**Comment by rayglover-ibm** [comment]
This change breaks linking on VS2015/CMake 3.7 for me; the `"${NODEJS_LINK_FLAGS}"` expression expands to a `;` delimited string, which is bad because we need a white-space delimited string for `LINK_FLAGS` (which itself is a string property).

**Comment by kkaefer** [comment]
This is a case for [`separate_arguments`](https://cmake.org/cmake/help/v3.7/command/separate_arguments.html).

**Comment by rayglover-ibm** [comment]
I think `seperate_arguments` does the opposite of what's needed. Do you have an example?

A naive way of doing this could be `string(REPLACE ";" " " LINK_FLAGS_STR "${NODEJS_LINK_FLAGS}")` and then:

```
set_target_properties(${NAME} PROPERTIES
    ...
    LINK_FLAGS "${LINK_FLAGS_STR}"
)
```

**Comment by kkaefer** [comment]
You're right, sorry.

**Pull request merged**
