### PR TITLE
convert NODEJS_LINK_FLAGS to space separated string

### PR DESCRIPTION
**Pull request by stixx200**

### CODE REVIEW

**Comment by gpean** [comment]
I think we also need to quote `${NODEJS_LINK_FLAGS}` when we use it in `set_target_properties`, otherwise I'm getting this error on ubuntu because `NODEJS_LINK_FLAGS` happens to be empty:

```
CMake Error at node_modules/node-cmake/NodeJS.cmake:610 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
```

**Comment by cjntaylor** [comment]
Thank you for the pull request. I decided to tackle this a different way but I really appreciate the input. Please update to 2.3.1 and let me know if you're still having issues.

**Comment by stixx200** [comment]
Thanks for fast response.
I still have issues with the linker flags. Now it seems that all linker flags are appended into one string. The problem is, that there are no spaces between the flags.
Something like `"${NODEJS_LINK_FLAG} "` would help.

**Comment by cjntaylor** [comment]
Fixed in 2.3.2

**Pull request closed without merging**
